# -*- coding: utf-8 -*-
"""celula_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Dxwcb03KfXFgl8NI-tGSL8VECVg1EJG
"""

import re
import certifi
import pandas as pd
from urllib.parse import quote_plus
from pymongo import MongoClient

# ─── 1. Conecta no Atlas (Chave Direta) ──────────────────────────────
# Chave inserida diretamente para facilitar a execução
MONGO_URI = "mongodb+srv://arthurcmarques:Artben0613@aulamongo.jofjspp.mongodb.net/"

m = re.match(r"(mongodb(?:\+srv)?://)([^:]+):([^@]+)@(.+)", MONGO_URI)
if m:
    schema, user, password, rest = m.groups()
    MONGO_URI = f"{schema}{quote_plus(user)}:{quote_plus(password)}@{rest}"

client = MongoClient(
    MONGO_URI,
    tlsCAFile=certifi.where(),
    serverSelectionTimeoutMS=15000,
)
client.admin.command("ping")
db = client["saude_campinas"]

print(f"✓ Conectado no Atlas")
print(f"   regioes:           {db.regioes.count_documents({})} documentos")
print(f"   estabelecimentos:  {db.estabelecimentos.count_documents({})} documentos")
print(f"   relacoes:          {db.relacoes.count_documents({})} documentos")