# -*- coding: utf-8 -*-
"""proj_integrador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DH_F3lQAMwTy8IiG5dOCQACy5MpD2Epn
"""

!pip install -q plotly networkx pandas requests

!pip install -q plotly networkx pandas requests pymongo[srv]

exec(open('/content/celula_2.py').read())

exec(open('/content/celula_3.py').read())

import os, json, shutil
from pathlib import Path
from google.colab import files

# Cria pasta dados/ a partir do MongoDB
DATA_DIR = Path("/content/dados")
DATA_DIR.mkdir(exist_ok=True)

# Exporta as 3 coleções como JSON
for col_name in ["regioes", "estabelecimentos", "relacoes"]:
    docs = list(db[col_name].find({}))
    arquivo = DATA_DIR / f"{col_name}.json"
    arquivo.write_text(
        json.dumps(docs, indent=2, ensure_ascii=False, default=str),
        encoding="utf-8"
    )
    print(f"   ✓ {col_name}.json — {len(docs)} documentos")

# Zipa a pasta
shutil.make_archive("/content/dados_campinas", "zip", "/content/dados")

print("\n📦 Arquivos disponíveis:")
for f in sorted(os.listdir("/content/dados")):
    tam = os.path.getsize(f"/content/dados/{f}")
    print(f"  dados/{f}  ({tam:,} bytes)")

print(f"\n  dashboard.html        ({os.path.getsize('/content/dashboard.html'):,} bytes)")
print(f"  dados_campinas.zip    ({os.path.getsize('/content/dados_campinas.zip'):,} bytes)")

print("\n⬇️  Iniciando downloads...")
files.download("/content/dashboard.html")
files.download("/content/dados_campinas.zip")